from abc import ABC, abstractmethod
from mosaic.core.models import MeshEvent
from mosaic.core.client import MeshClient

class BaseNode(ABC):
    def __init__(self, client: MeshClient):
        self._client = client
        self._running = False
    
    @abstractmethod
    async def process_event(self, event: MeshEvent): ...
    @abstractmethod
    async def on_start(self): ...
    @abstractmethod
    async def on_shutdown(self): ...
    async def start(self): ...
    async def _run_forever(self): ...
    async def _heartbeat_loop(self): ...
    async def _handle_stop_signal(self): ...