from typing import Dict

from mosaic.core.client import MeshClient
from mosaic.nodes.agent.base import AgentNode, Session
from mosaic.nodes.agent.enums import AgentNodeRunningMode

class DummyAgent(AgentNode):
    def __init__(
        self, 
        mesh_id: str, 
        node_id: str, 
        config: Dict[str, str], 
        client: MeshClient,
        mode: AgentNodeRunningMode
    ):
        super().__init__(mesh_id, node_id, config, client)

    async def create_session(self, mesh_id: str, node_id: str) -> Session: ...
    async def chat(self): ...
    async def program(self): ...
    async def on_start(self): ...
    async def on_shutdown(self): ...
    async def start_chat_mode(self): ...
    async def stop_chat_mode(self): ...
    async def start_program_mode(self): ...
    async def stop_program_mode(self): ...