from typing import AsyncIterator, Optional
from mosaic.core.models import MeshEvent
from mosaic.core.transport import TransportBackend

class RedisTransportBackend(TransportBackend):
    async def connect(self): ...
    async def disconnect(self): ...
    async def send(self, event: MeshEvent): ...
    async def receive(self) -> AsyncIterator[MeshEvent]:...
    async def ack(self, event: MeshEvent): ...
    async def nack(self, event: MeshEvent, reason: Optional[str] = None): ...