from typing import AsyncIterator
from mosaic.core.models import MeshEvent
from mosaic.core.transport import TransportBackend

class RedisTransportBackend(TransportBackend):
    async def connect(self): ...
    async def disconnect(self): ...
    async def send(self, event: MeshEvent) -> None: ...
    async def receive(self) -> AsyncIterator[MeshEvent]:...