from pathlib import Path
from typing import AsyncIterator, List, Optional
from mosaic.core.models import MeshEvent
from mosaic.core.transport import TransportBackend
from mosaic.core.types import MeshID, NodeID

class EventRepository:
    def __init__(self, db_path: Path): ...
    async def save(self, event: MeshEvent): ...
    async def fetch_pending(self, target_id: NodeID) -> List[MeshEvent]: ...

class SignalClient:
    def __init__(self, socket_dir: Path): ...
    async def notify(self, target_id: NodeID): ...

class SignalListener:
    def __init__(self, socket_path: Path): ...
    async def start(self): ...
    def __aiter__(self): ...

class SqliteTransportBackend(TransportBackend):
    def __init__(self, mesh_id: MeshID, node_id: NodeID):
        self._mesh_id = mesh_id
        self._node_id = node_id
        self._db_path = Path.home() / ".mosaic" / mesh_id / "events.db"
        self._socket_dir = Path.home() / ".mosaic" / mesh_id / "sockets"
        self._socket_path = self._socket_dir / f"{node_id}.sock"
        self._repo = EventRepository(self._db_path)
        self._signal_client = SignalClient(self._socket_dir)
        self._signal_listener = SignalListener(self._socket_path)

    async def connect(self): ...
    async def disconnect(self): ...
    async def send(self, event: MeshEvent):
        await self._repository.save(event)
        await self._signal_client.notify(event.target_id)

    async def receive(self) -> AsyncIterator[MeshEvent]: ...
    async def ack(self, event: MeshEvent): ...
    async def nack(self, event: MeshEvent, reason: Optional[str] = None): ...