from typing import Optional

from mosaic.core.models import MeshEvent
from mosaic.core.transport import TransportBackend

class SqliteTransportBackend(TransportBackend):
    async def connect(self): ...
    async def disconnect(self): ...
    async def send(self, event: MeshEvent): ...
    async def send_blocking(
        self, 
        event: MeshEvent, 
        timeout: float
    ) -> MeshEvent: ...
    async def receive(self) -> MeshEvent:...
    async def ack(self, event: MeshEvent): ...
    async def nack(self, event: MeshEvent, reason: Optional[str] = None): ...